version: "3.8"

networks:
  orb-core:
    name: orb-core
    driver: bridge
    external: true

services:
  prv-cunjur:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prv-cunjur
    restart: unless-stopped
    networks:
      - orb-core
    volumes:
      - ./public:/var/www/html